[project]
name = "explore-gefs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.81",
    "marimo>=0.10.2",
]
